log_root: data/task_logs/data4ResGRU/
out_dir: flowbot/residual_model/checkpoints2/
val_fraction: 0.2
seed: 42
seq_len: 10
warmup_len: 5
use_optitrack: true
l0: 82.0
lu: 13.5
alpha_deg: -30.0
hidden: 32
layers: 2
dropout: 0.1
epochs: 500
batch: 32
lr: 0.001
patience: 50
input_size: 9
best_val_loss: 0.08399438164161362
n_params: 12483
