data_dir: data/flow_tip_free_100g_mixed/
out_dir: flowbot/proprioception_model/checkpoints
load: '100'
val_fraction: 0.2
seed: 42
state: free_human
aug_alpha_min: 0.6
features: pwm,flow,K
arch: resmlp
hidden: 256
num_blocks: 4
dropout: 0.05
epochs: 500
batch: 64
lr: 0.001
patience: 100
no_plot: false
feature_indices:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
input_size: 9
best_val_loss: 0.03993745703535218
n_params: 566787
